#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : snabb
Version  : 2018.09
Release  : 2
URL      : https://github.com/snabbco/snabb/archive/v2018.09.tar.gz
Source0  : https://github.com/snabbco/snabb/archive/v2018.09.tar.gz
Summary  : Just-in-time compiler for Lua
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: snabb-bin = %{version}-%{release}
Requires: snabb-license = %{version}-%{release}
Patch1: 0001-fix-the-compile-error-occured-in-gcc-8.3.1-which-cau.patch

%description
Usage:
snabb wall <subcommand> <arguments...>
snabb wall --help
Available subcommands:

%package bin
Summary: bin components for the snabb package.
Group: Binaries
Requires: snabb-license = %{version}-%{release}

%description bin
bin components for the snabb package.


%package license
Summary: license components for the snabb package.
Group: Default

%description license
license components for the snabb package.


%prep
%setup -q -n snabb-2018.09
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554881116
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1554881116
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/snabb
cp COPYING %{buildroot}/usr/share/package-licenses/snabb/COPYING
cp lib/ljndpi/COPYING %{buildroot}/usr/share/package-licenses/snabb/lib_ljndpi_COPYING
cp lib/ljsyscall/COPYRIGHT %{buildroot}/usr/share/package-licenses/snabb/lib_ljsyscall_COPYRIGHT
cp lib/ljsyscall/doc/COPYRIGHT %{buildroot}/usr/share/package-licenses/snabb/lib_ljsyscall_doc_COPYRIGHT
cp lib/luajit/COPYRIGHT %{buildroot}/usr/share/package-licenses/snabb/lib_luajit_COPYRIGHT
cp lib/pflua/COPYING %{buildroot}/usr/share/package-licenses/snabb/lib_pflua_COPYING
cp lib/pflua/LICENSE %{buildroot}/usr/share/package-licenses/snabb/lib_pflua_LICENSE
cp src/apps/solarflare/COPYRIGHT %{buildroot}/usr/share/package-licenses/snabb/src_apps_solarflare_COPYRIGHT
install -D src/snabb %{buildroot}/usr/bin/snabb

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/snabb

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/snabb/COPYING
/usr/share/package-licenses/snabb/lib_ljndpi_COPYING
/usr/share/package-licenses/snabb/lib_ljsyscall_COPYRIGHT
/usr/share/package-licenses/snabb/lib_ljsyscall_doc_COPYRIGHT
/usr/share/package-licenses/snabb/lib_luajit_COPYRIGHT
/usr/share/package-licenses/snabb/lib_pflua_COPYING
/usr/share/package-licenses/snabb/lib_pflua_LICENSE
/usr/share/package-licenses/snabb/src_apps_solarflare_COPYRIGHT
